"""Motion generated by deciding, each frame, what the body should do next.

This replaces the generator, not the pipeline. The flywheel never defined what a
candidate *is* -- it calls something that returns a :class:`ClipResult` and then
captures, judges, ranks and repairs it -- so a different way of producing that
clip drops into the same loop.

WHAT THE OLD GENERATOR DID

    prompt -> plan_motion -> 7 phase primitives -> interpolate -> simulate

``PrimitiveKind`` is a vocabulary of *phases* (reach, preshape, contact, close,
lift, hold, recover), chosen once, before anything is observed, and the compiler
never calls the planner back. Physics ran afterwards and changed nothing. Five
"candidates" were the same program with the elbow swung a few degrees.

That is why the hand closed on a timer rather than on the object being between
its fingers, why the grip shape was fixed before the object was seen, and why
the plan was identical for every object. Those were not three bugs.

WHAT THIS DOES

    prompt
      -> a plan of what must be done, as ordered low-level steps
      -> each step as a Talmy product: FIGURE, GROUND, PATH, MOTION
      -> each frame: sense the situation, choose which primitive each body part
         should run this instant to advance the current product's goal

The primitives are the *per-part moves* in ``config/body_parts.v1.json`` -- 314
of them, which until now nothing in the motion path read. They are the controls;
the selector is what drives them.

WHAT IS AND IS NOT DECIDED BY A MODEL

The per-frame chooser is an interface, :class:`MoveSelector`, with two
implementations. :class:`GreedySelector` scores each candidate move by how much
it would reduce the current step's measured error, which is deterministic and
testable and needs no model. A VLM selector implements the same interface and
sees the same sensor readings. The architecture is the closed loop; which mind
sits in it is a separate choice, and pretending a greedy search is a VLM would
make the loop untestable.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Protocol

import numpy as np

from .body_parts import move_rotations, moves_for
from .kinematics import rig_kinematics
from .models import BonePose, Hand, SceneManifest, SceneObject, Vec3
from .talmy import MotionSituation, path_contour

#: Parts the selector may drive, and the moves it may choose for each. Kept to
#: the acting arm and hand: a grab that re-solves the legs every frame spends
#: its whole budget deciding not to move them.
def acting_parts(hand: Hand) -> tuple[str, ...]:
    side = hand.value
    return (
        f"{side}_shoulder",
        f"{side}_elbow",
        f"{side}_wrist",
        f"{side}_thumb",
        f"{side}_index",
        f"{side}_middle",
        f"{side}_ring",
        f"{side}_little",
    )


#: The one primitive that is solved rather than named. A reach is coordinated by
#: definition -- shoulder, elbow and wrist move together toward a point -- and
#: composing it from independently chosen per-part poses is a description of a
#: reach rather than the thing itself. Named like any other move so the trace,
#: the selector interface and the flywheel do not have to know the difference.
AIM_AT_FIGURE = "aim_at_figure"


def _aim_rotations(
    hand: Hand, sensing: Sensing, amplitude: float
) -> dict[str, Any]:
    """Arm rotations that aim the hand a fraction of the way to the object."""
    from .models import PrimitiveParameters, Vec3
    from .primitives import arm_pose_from_target, shoulder_position

    aim = _aim_point(hand, sensing, amplitude)
    arm, _ = arm_pose_from_target(
        hand,
        shoulder_position(hand),
        Vec3(x=float(aim[0]), y=float(aim[1]), z=float(aim[2])),
        PrimitiveParameters(),
        present_hand=False,
    )
    return arm


def _aim_point(hand: Hand, sensing: Sensing, amplitude: float) -> np.ndarray:
    """Where to send the WRIST so the FINGERTIPS arrive at the object.

    ``arm_pose_from_target`` places the hand bone's origin, and the point being
    steered is the mean of the fingertips, which trails it by most of a hand.
    Aiming the wrist straight at the object therefore stops a hand-length short
    however well the solver does its job -- measured, the approach error sat at
    0.0901 m and would not move, which is that offset almost exactly.

    The offset is read from the pose the hand is in, not assumed, because it
    changes as the fingers curl.
    """
    positions = rig_kinematics().canonical_positions(sensing.bones)
    wrist = np.asarray(positions[f"{hand.value}Hand"], dtype=float)
    lead = sensing.convergence - wrist
    goal = sensing.object_position - lead
    # Never past the goal. An amplitude is a fraction of the way there, and
    # allowing more than 1.0 extrapolates a WORLD POSITION rather than
    # travelling further along a path: at 1.5 the wrist is sent half a metre
    # beyond the object, the arm is flung, and the hand sweeps the block off the
    # table -- measured, 124 cm, from a loop that had been leaving it untouched.
    # Overshoot belongs to the digits closing, not to the arm arriving.
    reach = float(np.clip(amplitude, 0.0, 1.0))
    return wrist + (goal - wrist) * reach


@dataclass(frozen=True)
class Sensing:
    """What the body can actually tell about its situation this frame.

    Every field is something the simulation or the kinematics measured, not
    something the plan asserted. A selector that reads only this cannot smuggle
    in knowledge of where the object was authored to be -- which is the mistake
    that let a hand close on empty air and report a grasp, because the aperture
    was being measured against the object's authored pose while the simulated
    one had been knocked 9 cm away.
    """

    bones: dict[str, BonePose]
    object_position: np.ndarray
    tip_positions: dict[str, np.ndarray]
    convergence: np.ndarray
    contact_force_n: dict[str, float]
    opposed: bool
    time_s: float

    def loaded_digits(self, threshold_n: float = 0.5) -> tuple[str, ...]:
        return tuple(
            digit
            for digit, force in sorted(self.contact_force_n.items())
            if force >= threshold_n
        )


@dataclass
class Step:
    """One Talmy product: a thing that must be true before the next step starts.

    ``error`` is what the selector minimises and ``reached`` is what ends the
    step. They are separate because a step can be close enough to advance while
    its error is still nonzero, and because a step with no measurable goal is a
    step nothing can verify -- which is the state the old ``close`` phase was in
    when it fired on elapsed time.
    """

    name: str
    situation: MotionSituation
    error: Callable[[Sensing], float]
    reached: Callable[[Sensing], bool]
    active_parts: tuple[str, ...]
    #: Frames to spend before giving up and advancing anyway. A step that cannot
    #: be reached must not stall the whole motion silently.
    budget_frames: int = 45

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "figure": self.situation.figure,
            "path": self.situation.path,
            "motion": self.situation.motion,
            "ground": self.situation.ground,
            "active_parts": list(self.active_parts),
            "budget_frames": self.budget_frames,
        }


class MoveSelector(Protocol):
    """Chooses which primitive each active part runs this frame."""

    def choose(
        self, sensing: Sensing, step: Step, candidates: dict[str, tuple[str, ...]]
    ) -> dict[str, tuple[str, float]]:
        """Return, per part, the move to run and how much of it."""
        ...


def _tips(hand: Hand) -> dict[str, str]:
    side = hand.value
    return {
        digit: f"{side}{digit.title()}Distal"
        for digit in ("thumb", "index", "middle", "ring", "little")
    }


def sense(
    bones: dict[str, BonePose],
    hand: Hand,
    object_position: np.ndarray,
    contact_force_n: dict[str, float],
    opposed: bool,
    time_s: float,
) -> Sensing:
    """Read the situation from the pose and the running simulation."""
    positions = rig_kinematics().canonical_positions(bones)
    tips = {
        digit: np.asarray(positions[bone], dtype=float)
        for digit, bone in _tips(hand).items()
    }
    stack = np.vstack(list(tips.values()))
    return Sensing(
        bones=bones,
        object_position=np.asarray(object_position, dtype=float),
        tip_positions=tips,
        convergence=stack.mean(axis=0),
        contact_force_n=dict(contact_force_n),
        opposed=bool(opposed),
        time_s=float(time_s),
    )


#: A fingertip rests this far from the surface when the digit is touching it:
#: the collision capsules are 6.5-7.5 mm in radius, so a tip AT the surface is
#: already pressed into it by its own thickness.
_CONTACT_STANDOFF_M = 0.007


def _surface_distance(
    point: np.ndarray, figure: SceneObject, observed_centre: np.ndarray
) -> float:
    """Distance from a point to the object's surface, where the object IS.

    ``observed_centre`` comes from the running simulation rather than the
    scene's authored transform. Measuring against the authored pose is how a
    hand closing on empty air reported a grasp: the simulated block had been
    knocked 9 cm away and every geometric number was still being taken against
    the place it started.
    """
    half = np.asarray(
        [figure.dimensions_m.x, figure.dimensions_m.y, figure.dimensions_m.z],
        dtype=float,
    ) * 0.5
    delta = np.abs(np.asarray(point, dtype=float) - np.asarray(observed_centre, dtype=float))
    outside = np.maximum(delta - half, 0.0)
    inside = float(np.max(delta - half))
    return float(np.linalg.norm(outside)) if np.any(outside > 0) else inside


def decompose(
    situation: MotionSituation,
    scene: SceneManifest,
    hand: Hand,
) -> list[Step]:
    """The overall product, broken into the steps that achieve it.

    "pick up box" is one Talmy product -- MOVE the block OFF its support -- and
    it is not directly actionable: nothing about OFF says how a hand gets there.
    It decomposes into products that are: bring the hand TO the object, close
    AT it until it is held, then MOVE it OFF.

    Each carries its own measurable goal, so "am I done" is a reading rather
    than a stopwatch.
    """
    figure = scene.object_by_id(situation.figure)
    if figure is None:
        raise ValueError(f"figure {situation.figure!r} is not in the scene")
    side = hand.value
    arm = (f"{side}_shoulder", f"{side}_elbow", f"{side}_wrist")
    digits = (f"{side}_thumb", f"{side}_index", f"{side}_middle",
              f"{side}_ring", f"{side}_little")

    contour = path_contour(situation, scene)
    lift_target = float(contour.points[-1][1])

    #: The hand must be open wider than the object before it arrives, or the
    #: approach is a fist driven through it.
    span = float(np.linalg.norm([
        figure.dimensions_m.x, figure.dimensions_m.y, figure.dimensions_m.z]))

    def _spread(s: Sensing) -> float:
        """Widest distance between any two fingertips."""
        points = list(s.tip_positions.values())
        return max(
            float(np.linalg.norm(a - b))
            for index, a in enumerate(points)
            for b in points[index + 1:]
        )

    def approach_error(s: Sensing) -> float:
        """Distance to the object, plus whatever the hand is still closed by.

        Aiming the fingertip mean at the object's centre is right -- that is
        where a cage grasp puts it -- but only for a hand already open enough to
        arrive around the object rather than into it. With the digits left at
        their rest pose the approach became a fist driven at the block, and the
        block went on the floor: 124 cm, once the arm finally reached far enough
        to touch anything at all.

        Openness is scored as a shortfall against the object's own size, so it
        stops mattering the moment the hand is wide enough, and the term never
        competes with arriving.
        """
        distance = float(np.linalg.norm(s.convergence - s.object_position))
        shortfall = max(0.0, span - _spread(s))
        return distance + shortfall

    #: How far clear of the object the gross reach stops. One object-span, so
    #: the hand arrives beside what it is reaching for rather than on it.
    standoff = span

    def _standoff_point(s: Sensing) -> np.ndarray:
        """A point one span short of the object, on the hand's own approach line."""
        toward = s.object_position - s.convergence
        distance = float(np.linalg.norm(toward))
        if distance < 1e-6:
            return s.object_position
        return s.object_position - (toward / distance) * standoff

    def stage_error(s: Sensing) -> float:
        """Get NEXT TO the object, open, without touching it.

        Split from the fine approach because merging them made the gross reach
        drive straight onto the block. The loop would arrive correctly -- 0.064 m,
        the closest it had managed -- and knock the block off the table on the
        way in, because nothing said where to stop. The user's own decomposition
        had this step ("ensure box is near grip") and collapsing it was the
        mistake.
        """
        distance = float(np.linalg.norm(s.convergence - _standoff_point(s)))
        shortfall = max(0.0, span - _spread(s))
        return distance + shortfall

    def stage_reached(s: Sensing) -> bool:
        return stage_error(s) < 0.03

    def approach_reached(s: Sensing) -> bool:
        # Within a hand's own reach of the object, not touching it yet.
        return approach_error(s) < 0.045

    def grasp_error(s: Sensing) -> float:
        """How far each fingertip is from resting on the object's surface.

        Measured against the tips, not the hand's convergence point, because the
        digits are the parts this step activates and convergence is set by the
        arm. Scored on convergence, the fingers were minimising a number they
        could not move: the error drifted UP over the whole step, 0.1240 to
        0.1255, while the hand sat still and one finger happened to touch.

        A tip should come to rest ON the surface, so the target is a small
        positive standoff rather than zero -- a tip driven to the surface itself
        is already pressed into it by the digit's own thickness -- and going
        further in is penalised as much as stopping short, since a finger inside
        the object is what MuJoCo answers by throwing it.
        """
        gaps = [
            abs(_surface_distance(tip, figure, s.object_position) - _CONTACT_STANDOFF_M)
            for tip in s.tip_positions.values()
        ]
        return float(np.mean(gaps)) + (0.0 if s.opposed else 0.03)

    def grasp_reached(s: Sensing) -> bool:
        # The real test, and the one the old pipeline never applied: load on
        # opposing faces. Contact alone is a shove -- measured, the palm pressed
        # this block at 50 N from one side and slid it 5 cm.
        return s.opposed and len(s.loaded_digits()) >= 2

    def lift_error(s: Sensing) -> float:
        return abs(lift_target - float(s.object_position[1]))

    def lift_reached(s: Sensing) -> bool:
        return float(s.object_position[1]) >= lift_target - 0.01

    return [
        Step(
            name="bring the hand beside the object",
            situation=MotionSituation(
                figure="hand", path="TO", motion="MOVE",
                ground=situation.figure, source_text="move the hand next to the object"),
            error=stage_error,
            reached=stage_reached,
            active_parts=arm + digits,
            budget_frames=30,
        ),
        Step(
            name="bring the hand to the object",
            situation=MotionSituation(
                figure="hand", path="TO", motion="MOVE",
                ground=situation.figure, source_text="move the hand to the object"),
            error=approach_error,
            reached=approach_reached,
            active_parts=arm + digits,
        ),
        Step(
            name="close until the object is held",
            situation=MotionSituation(
                figure="hand", path="AT", motion="BEL", manner="GRASPED",
                ground=situation.figure, source_text="close on the object"),
            error=grasp_error,
            reached=grasp_reached,
            active_parts=digits,
        ),
        Step(
            name=f"move the object {situation.path}",
            situation=situation,
            error=lift_error,
            reached=lift_reached,
            active_parts=arm + digits,
        ),
    ]


@dataclass
class GreedySelector:
    """Picks the move that most reduces the step's error, one frame ahead.

    Deterministic and cheap: each candidate is applied to the current pose and
    the error re-read, which is forward kinematics rather than a simulation
    step. It is a baseline, not the intended mind -- but it is the thing a VLM
    selector has to beat, and without it there is no way to tell whether a model
    is choosing well or the loop is carrying it.
    """

    hand: Hand
    #: Blend toward the chosen move, per frame. A move is a target pose, not a
    #: teleport; stepping straight onto it is what produced the strikes the
    #: rate limiter was added to catch.
    rate: float = 0.25

    #: Magnitudes considered per move. Without these a part can only strike the
    #: poses somebody named: over all 990 arm move combinations the hand could
    #: get no closer than 17.4 cm to the block, which no selector can repair.
    #: The same combinations carrying a magnitude reach 2.4 cm.
    amplitudes: tuple[float, ...] = (0.25, 0.5, 0.75, 1.0, 1.25, 1.5)

    def choose(
        self, sensing: Sensing, step: Step, candidates: dict[str, tuple[str, ...]]
    ) -> dict[str, tuple[str, float]]:
        chosen: dict[str, tuple[str, float]] = {}

        # A goal-directed primitive, offered to the arm alongside the named
        # poses. Scaled named poses alone are not enough and the reason is the
        # search, not the vocabulary: reaching the block needs the shoulder,
        # elbow and wrist to change TOGETHER, and choosing one part at a time
        # against the others' current pose is coordinate descent, which stops at
        # the first place where no single part can improve. Measured, that is
        # 19.9 cm out, while the best joint choice is 2.4 cm.
        #
        # Rather than search the product space every frame -- 990 combinations
        # times six magnitudes each is 200k forward-kinematics passes -- the arm
        # gets one primitive that is already coordinated: aim the hand at a
        # point. That is what a reach IS, and composing it out of "abduct this
        # much, carry that much" was always a description of a reach rather than
        # the thing itself.
        arm_parts = {f"{self.hand.value}_{p}" for p in ("shoulder", "elbow", "wrist")}
        if arm_parts & set(candidates):
            aimed = self._reach(sensing, step)
            if aimed is not None:
                chosen.update(aimed)

        for part, moves in candidates.items():
            if part in chosen:
                continue
            best: tuple[float, str, float] | None = None
            for move in moves:
                for amplitude in self.amplitudes:
                    trial = dict(sensing.bones)
                    try:
                        rotations = move_rotations(part, move, amplitude)
                    except Exception:
                        continue
                    for name, rotation in rotations.items():
                        trial[name] = BonePose(rotation=rotation)
                    probe = sense(
                        trial, self.hand, sensing.object_position,
                        sensing.contact_force_n, sensing.opposed, sensing.time_s,
                    )
                    value = step.error(probe)
                    if best is None or value < best[0]:
                        best = (value, move, amplitude)
            if best is not None:
                chosen[part] = (best[1], best[2])
        return chosen

    def _reach(
        self, sensing: Sensing, step: Step
    ) -> dict[str, tuple[str, float]] | None:
        """Aim the hand at the object, and take it only if it beats standing still.

        Returned in the same (move, amplitude) shape as any other choice, where
        the amplitude is how far along the aim to travel this frame, so the loop
        does not need to know this one came from a solver.
        """
        from .models import PrimitiveParameters, Vec3
        from .primitives import arm_pose_from_target, shoulder_position

        target = sensing.object_position
        here = step.error(sensing)
        best: tuple[float, float] | None = None
        for amplitude in self.amplitudes:
            # Aim short of, at, or past the object: past is what closes the last
            # centimetres, because the fingertips trail the wrist.
            aim = _aim_point(self.hand, sensing, amplitude)
            try:
                arm, _ = arm_pose_from_target(
                    self.hand, shoulder_position(self.hand),
                    Vec3(x=float(aim[0]), y=float(aim[1]), z=float(aim[2])),
                    PrimitiveParameters(), present_hand=False)
            except Exception:
                continue
            trial = dict(sensing.bones)
            for bone, rotation in arm.items():
                trial[bone] = BonePose(rotation=rotation)
            probe = sense(trial, self.hand, sensing.object_position,
                          sensing.contact_force_n, sensing.opposed, sensing.time_s)
            value = step.error(probe)
            if best is None or value < best[0]:
                best = (value, amplitude)
        if best is None or best[0] >= here:
            return None
        self._aim_amplitude = best[1]
        return {
            f"{self.hand.value}_{part}": (AIM_AT_FIGURE, best[1])
            for part in ("shoulder", "elbow", "wrist")
        }



# ---------------------------------------------------------------------------
# The super-primitive layer.
#
# Everything the selector may call is here, and everything here is coordinated:
# each drives several parts at once toward a goal, and each resolves down to the
# same per-bone rotations a per-part move would have produced.
#
# The loop used to choose one atomic move per part per frame, and every failure
# it hit was a coordination that choice could not express. Reaching needs the
# shoulder, elbow and wrist together -- over all 990 combinations of their named
# poses the hand could get no closer than 17.4 cm to the block, and choosing one
# part at a time stalls at 19.9 cm. Opening the hand needs five digits together.
# Opposing the thumb needs the thumb and the finger it works against. Each time,
# the coordination had to be smuggled into an error function instead of being a
# thing the controller could ask for.
#
# So the controls are high level and they map down, rather than being low level
# and hoping the selector rediscovers the map every frame.
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class SuperPrimitive:
    """A coordinated action the selector can call, with the parts it drives."""

    name: str
    parts: tuple[str, ...]
    describes: str
    solve: Callable[[Sensing, Hand, float], dict[str, Any]]

    def to_dict(self) -> dict[str, Any]:
        return {"name": self.name, "parts": list(self.parts), "describes": self.describes}


def _arm_parts(hand: Hand) -> tuple[str, ...]:
    side = hand.value
    return (f"{side}_shoulder", f"{side}_elbow", f"{side}_wrist")


def _digit_parts(hand: Hand) -> tuple[str, ...]:
    side = hand.value
    return tuple(f"{side}_{d}" for d in ("thumb", "index", "middle", "ring", "little"))


def _solve_reach(sensing: Sensing, hand: Hand, amount: float) -> dict[str, Any]:
    """Aim the FINGERTIPS at the object, a fraction of the way there."""
    from .models import PrimitiveParameters, Vec3
    from .primitives import arm_pose_from_target, shoulder_position

    aim = _aim_point(hand, sensing, amount)
    arm, _ = arm_pose_from_target(
        hand, shoulder_position(hand),
        Vec3(x=float(aim[0]), y=float(aim[1]), z=float(aim[2])),
        PrimitiveParameters(), present_hand=False)
    return arm


def _solve_stand_off(sensing: Sensing, hand: Hand, amount: float) -> dict[str, Any]:
    """Aim short of the object, leaving room to arrive without touching."""
    from .models import PrimitiveParameters, Vec3
    from .primitives import arm_pose_from_target, shoulder_position

    toward = sensing.object_position - sensing.convergence
    distance = float(np.linalg.norm(toward))
    if distance < 1e-6:
        return {}
    goal = sensing.object_position - (toward / distance) * max(0.06, amount * 0.25)
    lead = sensing.convergence - np.asarray(
        rig_kinematics().canonical_positions(sensing.bones)[f"{hand.value}Hand"], dtype=float)
    aim = goal - lead
    arm, _ = arm_pose_from_target(
        hand, shoulder_position(hand),
        Vec3(x=float(aim[0]), y=float(aim[1]), z=float(aim[2])),
        PrimitiveParameters(), present_hand=False)
    return arm


def _solve_digits(hand: Hand, curl: float, opposition: float) -> dict[str, Any]:
    from .force_closure import digit_rotations

    return digit_rotations(
        hand, {d: curl for d in ("thumb", "index", "middle", "ring", "little")}, opposition)


def _solve_open(sensing: Sensing, hand: Hand, amount: float) -> dict[str, Any]:
    """Spread the hand. ``amount`` is how far toward fully open."""
    return _solve_digits(hand, curl=max(0.0, 0.35 * (1.0 - amount)), opposition=0.9)


def _solve_close(sensing: Sensing, hand: Hand, amount: float) -> dict[str, Any]:
    """Curl every digit together. ``amount`` is how far toward a full fist."""
    return _solve_digits(hand, curl=float(np.clip(amount, 0.0, 1.0)), opposition=0.9)


def _solve_oppose(sensing: Sensing, hand: Hand, amount: float) -> dict[str, Any]:
    """Carry the thumb across the palm toward the fingers it works against.

    The one coordination every grasp in this project has failed on: contacts
    exist in quantity -- the palm has pressed this block at 50 N -- but never on
    two opposing faces, so friction has nothing to work against and the object
    slides instead of lifting.
    """
    from .force_closure import digit_rotations

    rotations = digit_rotations(
        hand, {"thumb": float(np.clip(amount, 0.0, 1.0)), "index": 0.55,
               "middle": 0.55, "ring": 0.55, "little": 0.55},
        opposition=float(np.clip(0.3 + amount, 0.0, 1.2)))
    return rotations


def _solve_lift(sensing: Sensing, hand: Hand, amount: float) -> dict[str, Any]:
    """Raise the hand, carrying whatever it holds."""
    from .models import PrimitiveParameters, Vec3
    from .primitives import arm_pose_from_target, shoulder_position

    positions = rig_kinematics().canonical_positions(sensing.bones)
    wrist = np.asarray(positions[f"{hand.value}Hand"], dtype=float)
    aim = wrist + np.asarray([0.0, amount * 0.15, 0.0])
    arm, _ = arm_pose_from_target(
        hand, shoulder_position(hand),
        Vec3(x=float(aim[0]), y=float(aim[1]), z=float(aim[2])),
        PrimitiveParameters(), present_hand=False)
    return arm


def super_primitives(hand: Hand) -> tuple[SuperPrimitive, ...]:
    """Everything the selector may call, this frame."""
    return (
        SuperPrimitive("stand_off", _arm_parts(hand),
                       "bring the hand near the object without touching it",
                       _solve_stand_off),
        SuperPrimitive("reach_to", _arm_parts(hand),
                       "put the fingertips where the object is", _solve_reach),
        SuperPrimitive("open_hand", _digit_parts(hand),
                       "spread the digits wider than the object", _solve_open),
        SuperPrimitive("close_hand", _digit_parts(hand),
                       "curl every digit toward the object", _solve_close),
        SuperPrimitive("oppose_thumb", _digit_parts(hand),
                       "carry the thumb across the palm against the fingers",
                       _solve_oppose),
        SuperPrimitive("lift", _arm_parts(hand),
                       "raise the hand and whatever it holds", _solve_lift),
    )


@dataclass
class SuperPrimitiveSelector:
    """Chooses a coordinated action each frame, not a pose for each part.

    Scores every super primitive at every magnitude by the error it would leave,
    and takes the best. Six actions at six magnitudes is 36 trials a frame,
    fewer than the 62 the per-part selector needed and each one a coordinated
    change rather than a single joint moved against the others' current pose.

    This is the interface a VLM implements. It sees the same :class:`Sensing`
    and returns the same choice, so the two are directly comparable and the loop
    does not know which is driving.
    """

    hand: Hand
    magnitudes: tuple[float, ...] = (0.15, 0.3, 0.5, 0.7, 0.85, 1.0)

    def choose(self, sensing: Sensing, step: Step) -> tuple[str, float, dict[str, Any]]:
        here = step.error(sensing)
        best: tuple[float, str, float, dict[str, Any]] = (here, "hold", 0.0, {})
        for primitive in super_primitives(self.hand):
            if not (set(primitive.parts) & set(step.active_parts)):
                continue
            for amount in self.magnitudes:
                try:
                    rotations = primitive.solve(sensing, self.hand, amount)
                except Exception:
                    continue
                if not rotations:
                    continue
                trial = dict(sensing.bones)
                for bone, rotation in rotations.items():
                    trial[bone] = BonePose(rotation=rotation)
                probe = sense(trial, self.hand, sensing.object_position,
                              sensing.contact_force_n, sensing.opposed, sensing.time_s)
                value = step.error(probe)
                if value < best[0]:
                    best = (value, primitive.name, amount, rotations)
        return best[1], best[2], best[3]


def candidate_moves(step: Step) -> dict[str, tuple[str, ...]]:
    """The moves each active part may run this frame."""
    return {part: tuple(moves_for(part)) for part in step.active_parts}


@dataclass
class Trace:
    """What the loop decided, and what it was reading when it decided it."""

    steps: list[dict[str, Any]] = field(default_factory=list)
    decisions: list[dict[str, Any]] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "protocol": "closed_loop_generation_v1",
            "steps": self.steps,
            "decisions": self.decisions,
        }


def generate(
    situation: MotionSituation,
    scene: SceneManifest,
    hand: Hand,
    *,
    selector: MoveSelector | None = None,
    fps: float = 30.0,
    max_seconds: float = 4.0,
) -> tuple[list[Any], Trace]:
    """Run the loop and return the frames it produced.

    The simulation is stepped INSIDE the loop, and every sensor reading comes
    out of it. That is the whole difference from the old generator, which
    authored a motion, simulated it afterwards, and had no way for the result to
    influence anything.
    """
    import mujoco

    from .models import ClipFrame, Transform
    from .physics import (
        _contact_digit,
        _contact_snapshot,
        _embodied_xml,
        _frame_hand_landmarks,
        _hand_segment_pairs,
        _opposing_contact,
        _seed_embodied_bodies,
        _set_embodied_mocap,
        mj_to_app_position,
    )

    figure = scene.object_by_id(situation.figure)
    if figure is None:
        raise ValueError(f"figure {situation.figure!r} is not in the scene")
    selector = selector or SuperPrimitiveSelector(hand=hand)
    steps = decompose(situation, scene, hand)
    trace = Trace(steps=[s.to_dict() for s in steps])

    kinematics = rig_kinematics()
    pose: dict[str, BonePose] = {}
    segment_pairs = _hand_segment_pairs(hand)

    # Sized from the open hand, as the embodied simulation does.
    opening = ClipFrame(time_s=0.0, bones=pose, objects={})
    landmarks = _frame_hand_landmarks(opening, hand)
    lengths = {}
    for name, (start, end) in segment_pairs.items():
        digit = name.split("_")[1]
        tip = landmarks[f"{hand.value}{digit.title()}Tip"] if end is None else landmarks[end]
        lengths[name] = max(0.002, float(np.linalg.norm(tip - landmarks[start])) * 0.5 - 0.003)
    across = float(np.linalg.norm(
        landmarks[f"{hand.value}IndexProximal"] - landmarks[f"{hand.value}LittleProximal"]))
    along = float(np.linalg.norm(
        landmarks[f"{hand.value}MiddleProximal"] - landmarks[f"{hand.value}Hand"]))
    palm_half = np.asarray([max(0.025, across * 0.55), max(0.028, along * 0.58), 0.012])

    model = mujoco.MjModel.from_xml_string(
        _embodied_xml(figure, palm_half, lengths, scene.support_height_m))
    data = mujoco.MjData(model)
    block_body = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_BODY, "block")
    _seed_embodied_bodies(model, data, landmarks, hand, segment_pairs)
    mujoco.mj_forward(model, data)

    dt = float(model.opt.timestep)
    steps_per_frame = max(1, int(round((1.0 / fps) / dt)))
    frames: list[ClipFrame] = []
    index = 0
    spent = 0

    for frame_index in range(int(max_seconds * fps)):
        now = frame_index / fps
        # ---- sense, from the simulation that is running ----
        _names, _pen, details = _contact_snapshot(model, data)
        forces: dict[str, float] = {}
        for geom, _position, force, _normal in details:
            digit = _contact_digit(geom)
            if digit is not None:
                forces[digit] = max(forces.get(digit, 0.0), float(force))
        opposed = _opposing_contact(details) is not None
        observed = mj_to_app_position(data.xpos[block_body])
        reading = sense(pose, hand, observed, forces, opposed, now)

        # ---- has this product been achieved? ----
        step = steps[index]
        if step.reached(reading):
            trace.decisions.append({
                "time_s": round(now, 3), "step": step.name,
                "event": "reached", "error": round(step.error(reading), 5)})
            if index + 1 < len(steps):
                index += 1
                spent = 0
                step = steps[index]
        elif spent >= step.budget_frames:
            trace.decisions.append({
                "time_s": round(now, 3), "step": step.name,
                "event": "budget_exhausted", "error": round(step.error(reading), 5)})
            if index + 1 < len(steps):
                index += 1
                spent = 0
                step = steps[index]

        # ---- decide what each part does this instant ----
        action, amount, rotations = selector.choose(reading, step)
        spent += 1
        if frame_index % 5 == 0:
            trace.decisions.append({
                "time_s": round(now, 3), "step": step.name, "event": "chose",
                "action": action, "amount": amount,
                "error": round(step.error(reading), 5),
                "loaded": list(reading.loaded_digits()), "opposed": opposed})

        # ---- move toward the chosen pose, at a bounded rate ----
        target = dict(pose)
        for bone, rotation in rotations.items():
            target[bone] = BonePose(rotation=rotation)

        # ---- move toward it, bounded by the joint speed ceilings ----
        # A bone absent from the pose starts from rest rather than being exempt,
        # so the ceilings bind from the first frame. Without that the hand
        # crossed 0.9 m in four frames and reached its standoff before the
        # second decision was taken, which is a teleport with sensing attached
        # rather than a loop.
        pose = _rate_limited(
            pose, _blend(pose, target, getattr(selector, "rate", 0.25)), 1.0 / fps
        )

        # ---- drive the simulation from the pose actually taken ----
        current = ClipFrame(time_s=now, bones=pose, objects={})
        _set_embodied_mocap(
            model, data, _frame_hand_landmarks(current, hand), hand, segment_pairs)
        for _ in range(steps_per_frame):
            mujoco.mj_step(model, data)

        placed = mj_to_app_position(data.xpos[block_body])
        frames.append(ClipFrame(
            time_s=now, bones=dict(pose),
            objects={figure.id: Transform(
                translation=Vec3(x=float(placed[0]), y=float(placed[1]), z=float(placed[2])))},
        ))
    return frames, trace


def _rate_limited(
    current: dict[str, BonePose], target: dict[str, BonePose], dt: float
) -> dict[str, BonePose]:
    """Clamp each bone's per-frame rotation to its joint class's ceiling."""
    from scipy.spatial.transform import Rotation, Slerp

    from .models import Quat
    from .motion_limits import limit_for

    from .models import Quat as _Quat

    #: A bone absent from the pose is at its rest rotation, not exempt. Passing
    #: absent bones through unlimited meant the ceilings did not engage until a
    #: bone already existed -- and since the pose starts empty, the first frames
    #: were unbounded. The hand crossed 0.9 m in four frames and "reached" its
    #: standoff before the second decision was made.
    rest = _Quat(x=0.0, y=0.0, z=0.0, w=1.0)
    out = dict(current)
    for bone, pose in target.items():
        start = current.get(bone) or BonePose(rotation=rest)
        a, b = start.rotation, pose.rotation
        rotations = Rotation.from_quat([[a.x, a.y, a.z, a.w], [b.x, b.y, b.z, b.w]])
        delta = float(np.degrees((rotations[1] * rotations[0].inv()).magnitude()))
        ceiling = limit_for(bone) * dt
        if delta <= ceiling or delta < 1e-9:
            out[bone] = pose
            continue
        xyzw = Slerp([0.0, 1.0], rotations)([ceiling / delta]).as_quat()[0]
        out[bone] = BonePose(rotation=Quat(
            x=float(xyzw[0]), y=float(xyzw[1]), z=float(xyzw[2]), w=float(xyzw[3])))
    return out


def _blend(
    current: dict[str, BonePose], target: dict[str, BonePose], rate: float
) -> dict[str, BonePose]:
    """Move a fraction of the way toward the target, about the shortest arc."""
    from scipy.spatial.transform import Rotation, Slerp

    from .models import Quat

    out = dict(current)
    for bone, pose in target.items():
        start = current.get(bone)
        if start is None:
            out[bone] = pose
            continue
        a = start.rotation
        b = pose.rotation
        rotations = Rotation.from_quat([[a.x, a.y, a.z, a.w], [b.x, b.y, b.z, b.w]])
        xyzw = Slerp([0.0, 1.0], rotations)([float(np.clip(rate, 0.0, 1.0))]).as_quat()[0]
        out[bone] = BonePose(rotation=Quat(
            x=float(xyzw[0]), y=float(xyzw[1]), z=float(xyzw[2]), w=float(xyzw[3])))
    return out
