"""Run every demo prompt, record its trace, and emit a browsable studio page.

Refusals are run and recorded alongside the successes, deliberately. A gallery of
things that worked says nothing about what the system does when asked for
something it cannot do, and the five refusal stages -- firewall, planning,
binding, compilation, certification -- are the part of the design worth being
able to inspect.

The page inlines every trace but references the clips relatively, so it stays
around a megabyte and still opens by double-clicking, with no server.
"""

from __future__ import annotations

import argparse
import html
import json
from dataclasses import dataclass
from pathlib import Path

import numpy as np

from rigby_general.contact import probe_grasp
from rigby_general.pipeline import ingest_robot
from rigby_general.primitives import PrimitiveLibrary
from rigby_general.run import answer
from rigby_general.schema.inventory import load_inventory
from rigby_general.trace import TraceStore
from rigby_general.viewer import sample_track

import render_demo


ROOT = Path(__file__).resolve().parents[1]
ZOO_ROOT = ROOT / "assets" / "general" / "zoo"
EXOTIC_ROOT = ROOT / "assets" / "general" / "exotic"

# The zoo is generated by this repository; the exotic set is fetched from an
# outside project and pinned. Keeping both in one studio is the point -- a claim
# about arbitrary robots is only worth as much as the robots nobody here wrote.
ROBOT_ROOTS = (ZOO_ROOT, EXOTIC_ROOT)


def discover() -> dict[str, Path]:
    """Every uploadable model across both roots, by id."""

    found: dict[str, Path] = {}
    for root in ROBOT_ROOTS:
        if not root.is_dir():
            continue
        for directory in sorted(root.iterdir()):
            source = directory / "robot.urdf"
            if source.is_file():
                found[directory.name] = source
    return found

SHARED_PROMPT = "reach out as far as you can and then come back"

PER_ROBOT_PROMPTS: dict[str, tuple[str, ...]] = {
    "zoo_tool_arm": ("sweep slowly across in front of you",),
    "zoo_jaw_arm": ("wave three times",),
    "zoo_hand_arm": ("trace a big circle",),
    "zoo_dual_arm": ("lower the tool down toward the table",),
    "zoo_compact_arm": ("reach out quickly, just a little",),
    "zoo_long_arm": ("sweep across the workspace, then hold still",),
    # The third-party arms get prompts of the same kind, not easier ones.
    "iiwa7": ("trace a big circle", "reach out slowly and hold there"),
    "kuka_lwr": ("sweep across in front of you", "wave twice"),
    "panda": ("reach out as far as you can, quickly", "trace a slow circle"),
}

# One of each refusal, so the studio shows what "no" looks like at every stage.
REFUSAL_PROMPTS: tuple[tuple[str, str], ...] = (
    ("zoo_jaw_arm", "drive across the room and open the door"),
    ("zoo_jaw_arm", "make me a sandwich"),
    ("zoo_jaw_arm", "hand it over to your other arm"),
    ("zoo_tool_arm", "pick it up and hold it"),
)


@dataclass(frozen=True, slots=True)
class Loaded:
    robot: object
    records: tuple
    failures: tuple
    centre: np.ndarray


def load(robot_id: str, library: PrimitiveLibrary, source: Path) -> Loaded:
    robot = ingest_robot(source, robot_id=robot_id)
    scale = robot.morphology.scale
    return Loaded(
        robot=robot,
        records=library.load(robot_id),
        failures=library.load_failures(robot_id),
        centre=np.array(
            [
                scale.workspace_centroid_m.x,
                scale.workspace_centroid_m.y,
                scale.workspace_centroid_m.z,
            ]
        ),
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--library", type=Path, default=ROOT / "robots")
    parser.add_argument("--out", type=Path, default=ROOT / "results")
    parser.add_argument("--no-render", action="store_true")
    arguments = parser.parse_args()

    inventory = load_inventory()
    library = PrimitiveLibrary(arguments.library)
    store = TraceStore(arguments.out)

    sources = discover()

    # Ingest everything first. A model that will not ingest cannot be prompted,
    # and *why* it was refused is a result worth recording rather than a reason
    # to quietly drop it from the run list.
    intake: list[dict[str, object]] = []
    run_tracks: dict[str, dict] = {}
    robot_ids: list[str] = []
    cache: dict[str, Loaded] = {}
    for robot_id, source in sources.items():
        origin = "zoo" if source.is_relative_to(ZOO_ROOT) else "third-party"
        try:
            loaded = load(robot_id, library, source)
        except Exception as error:  # noqa: BLE001 - the refusal is the record
            code = getattr(getattr(error, "code", None), "value", None)
            intake.append(
                {
                    "robot_id": robot_id,
                    "origin": origin,
                    "accepted": False,
                    "error": type(error).__name__,
                    "code": code,
                    "detail": str(error),
                }
            )
            print(f"{robot_id:<18} {'REFUSED@intake':<22} {code or type(error).__name__}")
            continue

        cache[robot_id] = loaded
        robot_ids.append(robot_id)
        morphology = loaded.robot.morphology
        intake.append(
            {
                "robot_id": robot_id,
                "origin": origin,
                "accepted": True,
                "morphology_class": morphology.morphology_class.value,
                "dofs": len(loaded.robot.manifest.dofs),
                "reach_m": round(morphology.scale.reach_radius_m, 3),
                "mass_kg": round(morphology.scale.total_mass_kg, 2),
                "effectors": [
                    {"kind": e.kind.value, "name": e.name} for e in morphology.effectors
                ],
                "notes": [note.detail for note in loaded.robot.integrity.notes],
            }
        )

    jobs: list[tuple[str, str]] = []
    for robot_id in robot_ids:
        jobs.append((robot_id, SHARED_PROMPT))
        for prompt in PER_ROBOT_PROMPTS.get(robot_id, ()):
            jobs.append((robot_id, prompt))
    jobs.extend(
        (robot_id, prompt)
        for robot_id, prompt in REFUSAL_PROMPTS
        if robot_id in cache
    )

    for robot_id, prompt in jobs:
        if robot_id not in cache:
            continue
        loaded = cache[robot_id]
        robot = loaded.robot

        result = answer(
            prompt,
            robot.manifest,
            robot.finalized.model,
            inventory,
            loaded.records,
            loaded.failures,
        )
        trace = result.trace

        clip_bytes = None
        if result.accepted and not arguments.no_render:
            frames = render_demo.render_trace(
                robot.finalized.model,
                result.certification.trace.qpos,
                result.certification.trace.times_s,
                centre=loaded.centre,
                reach=robot.morphology.scale.reach_radius_m,
            )
            scratch = arguments.out / "_scratch.gif"
            render_demo.write_gif(frames, scratch)
            clip_bytes = scratch.read_bytes()
            scratch.unlink(missing_ok=True)

        if result.accepted:
            # The simulated rollout, resampled for scrubbing. Same trace the
            # gates judged -- the viewer shows what the robot did, not the plan.
            run_tracks[trace.trace_id] = sample_track(
                result.certification.trace.times_s,
                result.certification.trace.qpos,
            )

        store.write(trace, clip_bytes=clip_bytes)
        verdict = "ok    " if result.accepted else f"refused@{result.failure_stage}"
        print(f"{robot_id:<18} {verdict:<22} {prompt[:52]}")

    # Contact probes. Every attempt is rendered, not only the ones that hold: a
    # failed grasp is the more informative clip, because you can watch the block
    # get knocked away or squeezed through the jaws instead of reading a gate
    # code and guessing.
    for robot_id in robot_ids:
        loaded = cache[robot_id]
        robot = loaded.robot

        outcome = probe_grasp(
            robot.manifest, robot.mjcf_xml, robot.finalized.model
        )
        clip_bytes = None
        if outcome.result is not None and not arguments.no_render:
            frames = render_demo.render_trace(
                outcome.scene.model,
                outcome.result.qpos,
                outcome.result.times_s,
                centre=np.asarray(outcome.scene.block_position_m),
                reach=robot.morphology.scale.reach_radius_m * 0.45,
            )
            scratch = arguments.out / "_scratch.gif"
            render_demo.write_gif(frames, scratch)
            clip_bytes = scratch.read_bytes()
            scratch.unlink(missing_ok=True)

        store.write(outcome.trace, clip_bytes=clip_bytes)
        verdict = (
            "held  "
            if outcome.trace.accepted
            else f"failed@{outcome.trace.failure['stage']}"
        )
        print(f"{robot_id:<18} {verdict:<22} grasp probe: pick up the block")

    (arguments.out / 'intake.json').write_text(
        json.dumps(intake, indent=2), encoding='utf-8'
    )
    page = build_page(store, arguments.library, intake, run_tracks)
    (arguments.out / "studio.html").write_text(page, encoding="utf-8")
    print(f"\n{len(store.list_ids())} traces -> {arguments.out / 'studio.html'}")
    return 0


# --------------------------------------------------------------------------
# The page
# --------------------------------------------------------------------------


def build_page(
    store: TraceStore,
    library_root: Path,
    intake: list[dict] | None = None,
    run_tracks: dict[str, dict] | None = None,
) -> str:
    traces = [store.load(trace_id) for trace_id in store.list_ids()]
    library = PrimitiveLibrary(library_root)

    robots: dict[str, dict] = {}
    for trace in traces:
        robots.setdefault(trace["robot_id"], trace["robot"])

    libraries = {}
    for robot_id in robots:
        summary = library.load_summary(robot_id)
        records = library.load(robot_id)
        failures = library.load_failures(robot_id)
        certified: dict[str, list[str]] = {}
        for record in records:
            certified.setdefault(record.entry_id, []).append(record.remove)
        refused: dict[str, str] = {}
        for failure in failures:
            if failure.entry_id not in certified:
                refused[failure.entry_id] = failure.failed_gate or failure.failure_code
        libraries[robot_id] = {
            "afforded": list(summary.afforded_entry_ids) if summary else [],
            "certified_count": len(records),
            "attempted": summary.attempted if summary else None,
            "yield": round(summary.yield_fraction, 3) if summary else None,
            "coverage": round(summary.schema_coverage, 3) if summary else None,
            "elapsed_seconds": round(summary.elapsed_seconds, 1) if summary else None,
            "certified": {k: sorted(v) for k, v in sorted(certified.items())},
            "refused": dict(sorted(refused.items())),
        }

    audit_path = ROOT / "docs" / "audit-report.json"
    audit = (
        json.loads(audit_path.read_text(encoding="utf-8"))
        if audit_path.is_file()
        else None
    )

    inventory = load_inventory()
    schema_rows = [
        {
            "id": entry.entry_id,
            "gloss": entry.gloss,
            "kind": entry.schema.kind.value,
            "requires": sorted(item.value for item in entry.requires),
        }
        for entry in sorted(inventory.entries, key=lambda item: item.entry_id)
    ]

    payload = json.dumps(
        {
            "traces": traces,
            "robots": robots,
            "libraries": libraries,
            "audit": audit,
            "intake": intake or [],
            "inventory": schema_rows,
        },
        indent=None,
        sort_keys=True,
    )

    viewer = json.dumps(
        {"robots": _viewer_robots(), "runs": run_tracks or {}},
        separators=(",", ":"),
        sort_keys=True,
    )
    viewer_js = "\n".join(
        (Path(__file__).resolve().parent / name).read_text(encoding="utf-8")
        for name in ("studio_viewer.js", "studio_views.js")
    )

    return (
        _TEMPLATE.replace("__DATA__", payload)
        .replace("__VIEWER__", viewer)
        .replace("__VIEWER_JS__", viewer_js)
        .replace("__COUNT__", str(len(traces)))
    )


def _viewer_robots() -> dict[str, dict]:
    """Geometry and primitive tracks, from whatever export_viewer.py left behind.

    Missing is not fatal and must not be: the studio still builds without them,
    and every player says which command would produce the geometry it wants. A
    rebuild that silently dropped the 3D would be worse than one that explains
    itself.
    """

    directory = ROOT / "results" / "viewer"
    if not directory.is_dir():
        return {}
    out: dict[str, dict] = {}
    for path in sorted(directory.glob("*.json")):
        try:
            out[path.stem] = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as error:  # pragma: no cover
            print(f"{'':18} !! viewer payload {path.name}: {error}")
    return out


_TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Rigby General - Trace Studio</title>
<style>
:root{
  --bg:#f7f7f5; --panel:#fff; --ink:#16171a; --muted:#6b6f76; --line:#e2e2df;
  --accent:#2f6f4f; --warn:#8a5a12; --bad:#9b2c2c; --code:#f0f0ed;
  --chip:#ececeb;
}
@media (prefers-color-scheme: dark){
  :root:not([data-theme=light]){
    --bg:#121316; --panel:#191a1e; --ink:#e8e8e6; --muted:#9a9ea6; --line:#2a2c31;
    --accent:#6cc196; --warn:#d8a657; --bad:#e07070; --code:#1f2125;
    --chip:#24262b;
  }
}
:root[data-theme=dark]{
  --bg:#121316; --panel:#191a1e; --ink:#e8e8e6; --muted:#9a9ea6; --line:#2a2c31;
  --accent:#6cc196; --warn:#d8a657; --bad:#e07070; --code:#1f2125; --chip:#24262b;
}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
  font:14px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif}
header{padding:18px 22px;border-bottom:1px solid var(--line);background:var(--panel);
  display:flex;gap:18px;align-items:baseline;flex-wrap:wrap;position:sticky;top:0;z-index:5}
h1{font-size:16px;margin:0;letter-spacing:.2px}
header .sub{color:var(--muted);font-size:12.5px}
header .spacer{flex:1}
button.tab{background:none;border:1px solid var(--line);color:var(--ink);
  padding:5px 11px;border-radius:6px;cursor:pointer;font-size:12.5px}
button.tab[aria-selected=true]{background:var(--accent);border-color:var(--accent);color:#fff}
main{display:grid;grid-template-columns:minmax(260px,330px) 1fr;gap:0;
  align-items:start;min-height:calc(100vh - 61px)}
@media (max-width:860px){main{grid-template-columns:1fr}}
/* Only the run browser has a list beside it. Every other view hides it, and a
   hidden grid item leaves its track behind -- so the detail pane lands in the
   330px column meant for the list and the whole view renders in a gutter. */
main[data-view]:not([data-view="runs"]){grid-template-columns:minmax(0,1fr)}
/* The 1000px cap is a reading measure for prose-heavy views. The explorer is
   two working columns and wants the room. */
main[data-view="explorer"] #detail{max-width:1720px}
#list{border-right:1px solid var(--line);background:var(--panel);
  max-height:calc(100vh - 61px);overflow:auto;position:sticky;top:61px}
.group{padding:9px 16px 4px;font-size:11px;letter-spacing:.08em;text-transform:uppercase;
  color:var(--muted);border-top:1px solid var(--line)}
.group:first-child{border-top:none}
.item{padding:9px 16px;border-bottom:1px solid var(--line);cursor:pointer;display:block;
  width:100%;text-align:left;background:none;border-left:3px solid transparent;color:inherit;
  font:inherit}
.item:hover{background:var(--chip)}
.item[aria-current=true]{border-left-color:var(--accent);background:var(--chip)}
.item .p{font-weight:600}
.item .m{color:var(--muted);font-size:12px;margin-top:2px;display:flex;gap:8px;flex-wrap:wrap}
#detail{padding:22px 26px;max-width:1000px}
section{margin-bottom:26px}
h2{font-size:13px;letter-spacing:.07em;text-transform:uppercase;color:var(--muted);
  margin:0 0 10px;font-weight:600}
.prompt{background:var(--panel);border:1px solid var(--line);border-left:3px solid var(--accent);
  padding:13px 16px;border-radius:6px;font-size:16px}
.meta{display:flex;gap:10px;flex-wrap:wrap;margin-top:10px}
.chip{background:var(--chip);border-radius:999px;padding:3px 10px;font-size:12px;color:var(--muted)}
.chip b{color:var(--ink);font-weight:600}
img.clip{max-width:100%;border:1px solid var(--line);border-radius:6px;display:block;background:#000}
.stage{border:1px solid var(--line);border-radius:6px;margin-bottom:8px;background:var(--panel);
  overflow:hidden}
.stage>summary{padding:10px 14px;cursor:pointer;display:flex;gap:11px;align-items:baseline;
  list-style:none}
.stage>summary::-webkit-details-marker{display:none}
.stage .dot{width:8px;height:8px;border-radius:50%;flex:0 0 auto;background:var(--accent)}
.stage.refused .dot{background:var(--bad)}
.stage .name{font-weight:600;min-width:98px}
.stage .say{color:var(--muted);flex:1}
.stage .ms{color:var(--muted);font-variant-numeric:tabular-nums;font-size:12px}
.stage .body{padding:0 14px 12px}
pre{background:var(--code);border-radius:5px;padding:11px 13px;overflow:auto;
  font:12px/1.5 ui-monospace,SFMono-Regular,Menlo,monospace;margin:0}
table{border-collapse:collapse;width:100%;font-size:12.5px}
th,td{text-align:left;padding:6px 9px;border-bottom:1px solid var(--line);vertical-align:top}
th{color:var(--muted);font-weight:600;font-size:11px;letter-spacing:.05em;text-transform:uppercase}
td.mono,th.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:11.5px}
.hash{font-family:ui-monospace,Menlo,monospace;font-size:11.5px;color:var(--muted);
  word-break:break-all}
.ok{color:var(--accent);font-weight:600}
.bad{color:var(--bad);font-weight:600}
.warn{color:var(--warn);font-weight:600}
.note{color:var(--muted);font-size:12.5px;margin-top:8px}
.card{background:var(--panel);border:1px solid var(--line);border-radius:6px;padding:14px 16px}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:10px}
.slots{display:grid;grid-template-columns:repeat(auto-fill,minmax(112px,1fr));gap:7px;margin-top:8px}
.slot{background:var(--chip);border-radius:5px;padding:6px 9px}
.slot .k{font-size:10.5px;letter-spacing:.05em;text-transform:uppercase;color:var(--muted)}
.slot .v{font-family:ui-monospace,Menlo,monospace;font-size:12px;margin-top:1px}
.slot.zero .v{color:var(--muted)}
.player{border:1px solid var(--line);border-radius:8px;overflow:hidden;
  background:linear-gradient(180deg,#12151c,#0d1014)}
.viewer{position:relative;width:100%;height:420px}
.viewer-canvas{width:100%;height:100%;display:block;touch-action:none;cursor:grab}
.viewer-canvas:active{cursor:grabbing}
.viewer-error{padding:16px;color:var(--warn);font-size:13px}
.transport{display:flex;align-items:center;gap:9px;padding:8px 10px;
  border-top:1px solid var(--line);background:var(--panel)}
.tbtn{min-width:32px;height:28px;border:1px solid var(--line);border-radius:5px;
  background:var(--chip);color:var(--fg);cursor:pointer;font-size:12px}
.tbtn:hover{border-color:var(--accent)}
.tbtn.wide{width:100%;margin-top:8px}
.scrub{flex:1;accent-color:var(--accent)}
.clock{font-family:ui-monospace,Menlo,monospace;font-size:11.5px;color:var(--muted);
  min-width:104px;text-align:right}
.speed,.tlab{font-size:11.5px;color:var(--muted)}
.speed{background:var(--chip);color:var(--fg);border:1px solid var(--line);
  border-radius:5px;height:28px}
.timeline{display:flex;gap:2px;margin:10px 0 6px;height:30px}
.phase{position:relative;border-radius:4px;background:var(--chip);cursor:pointer;
  display:flex;align-items:center;justify-content:center;overflow:hidden;
  border:1px solid transparent;transition:border-color .1s}
.phase span{font-size:10.5px;color:var(--muted);padding:0 5px;white-space:nowrap;
  text-overflow:ellipsis;overflow:hidden}
.phase.action{background:#1b2740}
.phase.recovery{background:#231d2e}
.phase.active{border-color:var(--accent)}
.phase.active span{color:var(--fg)}
.segs{display:flex;flex-direction:column;gap:8px;margin-top:10px}
.seg{border:1px solid var(--line);border-radius:6px;background:var(--panel)}
.seg-head{display:flex;align-items:center;gap:10px;padding:8px 11px;
  border-bottom:1px solid var(--line)}
.seg-head .rel{font-size:11px;color:var(--muted)}
.seg-head .span{margin-left:auto;font-family:ui-monospace,Menlo,monospace;
  font-size:11px;color:var(--accent);cursor:pointer}
.seg-body{padding:9px 11px}
.bound{margin-top:7px;font-size:12px}
.bound code{background:var(--code);padding:1px 5px;border-radius:4px}
.matrix td.cell{text-align:center;font-size:15px;width:74px}
.matrix td.cell.yes{color:var(--accent)}
.matrix td.cell.no{color:#4a5162}
.matrix td.cell.na{color:#333a47}
.matrix tr.used{background:rgba(94,234,212,0.05)}
.tag{font-size:9.5px;letter-spacing:.05em;text-transform:uppercase;
  background:var(--chip);border-radius:3px;padding:1px 5px;color:var(--accent)}
.na{color:var(--muted)}
.explorer{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(280px,1fr);
  gap:14px;align-items:start}
@media (min-width:901px){.ecol:first-child{position:sticky;top:12px}}
@media (max-width:900px){.explorer{grid-template-columns:1fr}}
.ecol{min-width:0;overflow:hidden}
/* Segment keys and site names are long and have no spaces, so they will not
   wrap on their own -- and an unwrapped one overflows its grid column and
   paints across the next. */
.ecol .note,.slot .v,.hash,.seg-body .note{overflow-wrap:anywhere;word-break:break-word}
.card{overflow:hidden}
.ecol h3{font-size:12px;letter-spacing:.05em;text-transform:uppercase;
  color:var(--muted);margin:0 0 7px}
.ecol h3.spaced{margin-top:16px}
.robotpick,.pchips{display:flex;flex-wrap:wrap;gap:6px}
.chip{border:1px solid var(--line);border-radius:5px;background:var(--chip);
  color:var(--muted);cursor:pointer;font-size:11.5px;padding:4px 9px;
  font-family:ui-monospace,Menlo,monospace}
.chip:hover{border-color:var(--accent);color:var(--fg)}
.chip.on{border-color:var(--accent);color:var(--accent);background:rgba(94,234,212,0.08)}
.joints{display:flex;flex-direction:column;gap:5px}
.jrow{display:grid;grid-template-columns:minmax(0,1fr) 1.25fr auto;gap:8px;
  align-items:center}
.jrow label{font-size:10.5px;color:var(--muted);overflow:hidden;
  text-overflow:ellipsis;white-space:nowrap}
.jslider{accent-color:var(--accent);width:100%}
.jval{font-size:10.5px;color:var(--muted);min-width:46px;text-align:right}
.plist{display:flex;flex-direction:column;gap:8px;max-height:460px;overflow:auto}
.pgroup .pname{font-size:11px;color:var(--muted);margin-bottom:4px}
</style>
</head>
<body>
<header>
  <h1>Rigby General &mdash; Trace Studio</h1>
  <span class="sub">__COUNT__ runs &middot; every stage recorded</span>
  <span class="spacer"></span>
  <button class="tab" data-view="runs" aria-selected="true">Runs</button>
  <button class="tab" data-view="invariance" aria-selected="false">Schema invariance</button>
  <button class="tab" data-view="contact" aria-selected="false">Contact</button>
  <button class="tab" data-view="library" aria-selected="false">Primitive libraries</button>
  <button class="tab" data-view="explorer" aria-selected="false">Explorer</button>
  <button class="tab" data-view="intake" aria-selected="false">Intake</button>
  <button class="tab" data-view="audit" aria-selected="false">Audit</button>
</header>
<main>
  <nav id="list"></nav>
  <div id="detail"></div>
</main>
<script id="data" type="application/json">__DATA__</script>
<script id="viewer-data" type="application/json">__VIEWER__</script>
<script>
__VIEWER_JS__
</script>
<script>
const DATA = JSON.parse(document.getElementById('data').textContent);
const VIEWER = JSON.parse(document.getElementById('viewer-data').textContent);
const esc = s => String(s ?? '').replace(/[&<>"]/g, c => (
  {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const num = (v, d=3) => (v === null || v === undefined) ? '&mdash;' : Number(v).toFixed(d);
let view = 'runs', current = DATA.traces.findIndex(t => t.accepted);
if (current < 0) current = 0;

/* Traces that share a role-normalized hash are the same body-neutral reading of
   the same request. Counting them is the whole magnitude-neutrality claim. */
function hashGroups(){
  const groups = new Map();
  DATA.traces.forEach(t => {
    if (!t.role_normalized_hash) return;
    if (!groups.has(t.role_normalized_hash)) groups.set(t.role_normalized_hash, []);
    groups.get(t.role_normalized_hash).push(t);
  });
  return groups;
}

function renderList(){
  const el = document.getElementById('list');
  // Tell the layout which view it is showing, so it can drop the list's grid
  // track rather than leaving the detail pane sitting in it.
  document.querySelector('main').dataset.view = view;
  if (view !== 'runs'){ el.innerHTML = ''; el.style.display = 'none'; return; }
  el.style.display = '';
  const rows = DATA.traces.map((t,i)=>({t,i}));
  const prompts = rows.filter(x => (x.t.kind || 'prompt') === 'prompt');
  const probes  = rows.filter(x => x.t.kind === 'contact_probe');
  const accepted = prompts.filter(x=>x.t.accepted);
  const refused  = prompts.filter(x=>!x.t.accepted);
  const row = ({t,i}) => `
    <button class="item" aria-current="${i===current}" onclick="select(${i})">
      <div class="p">${esc(t.prompt)}</div>
      <div class="m">
        <span>${esc(t.robot_id)}</span>
        ${t.kind === 'contact_probe'
          ? (t.accepted
              ? `<span class="ok">held</span><span>${(t.grasp.lift_height_m*1000).toFixed(0)} mm lift</span>`
              : `<span class="bad">${esc(t.failure?.code)}</span>`)
          : (t.accepted
              ? `<span class="ok">certified</span><span>${num(t.grounded?.duration_s,1)}s</span>`
              : `<span class="bad">refused @ ${esc(t.failure?.stage)}</span>`)}
      </div>
    </button>`;
  el.innerHTML =
    `<div class="group">Certified &middot; ${accepted.length}</div>` +
    accepted.map(row).join('') +
    `<div class="group">Refused &middot; ${refused.length}</div>` +
    refused.map(row).join('') +
    (probes.length
      ? `<div class="group">Contact probes &middot; ${probes.length}</div>`
        + probes.map(row).join('')
      : '');
}

function slotGrid(seg){
  const slots = [
    ['vector', seg.vector], ['conformation', seg.conformation],
    ['deixis', seg.deixis], ['contour', seg.contour], ['stative', seg.stative],
    ['figure', seg.figure], ['ground', seg.ground],
    ['remove', seg.remove], ['frame', seg.frame], ['boundary', seg.boundary],
  ].filter(([,v]) => v);
  const manner = Object.entries(seg.manner || {})
    .filter(([,v]) => v !== 0)
    .map(([k,v]) => [k, v > 0 ? `+${v}` : String(v)]);
  if (seg.repetition_count) manner.push(['count', `${seg.repetition_count}x`]);
  return `
    <div class="slots">
      ${slots.map(([k,v]) => `<div class="slot"><div class="k">${k}</div><div class="v">${esc(v)}</div></div>`).join('')}
    </div>
    <div class="note">Manner &mdash; ordinals relative to this robot's own neutral pace and scale.</div>
    <div class="slots">
      ${manner.length
        ? manner.map(([k,v]) => `<div class="slot"><div class="k">${k}</div><div class="v">${esc(v)}</div></div>`).join('')
        : `<div class="slot zero"><div class="k">all axes</div><div class="v">neutral</div></div>`}
    </div>`;
}

function renderRun(){
  const t = DATA.traces[current];
  if (!t) return '<p>No runs recorded.</p>';
  const g = hashGroups().get(t.role_normalized_hash) || [];
  const others = g.filter(x => x.robot_id !== t.robot_id);
  const segs = t.schema_program?.segments_readable || [];

  return `
  <section>
    <h2>Prompt</h2>
    <div class="prompt">${esc(t.prompt)}</div>
    <div class="meta">
      <span class="chip">robot <b>${esc(t.robot_id)}</b></span>
      <span class="chip">${esc(t.robot.morphology_class)}</span>
      <span class="chip">reach <b>${num(t.robot.reach_radius_m)} m</b></span>
      <span class="chip">dof <b>${t.robot.dof}</b></span>
      <span class="chip">${t.robot.effectors.map(e=>esc(e.kind)).join(', ')}</span>
      <span class="chip">${t.accepted ? '<b class="ok">certified</b>' : '<b class="bad">refused</b>'}</span>
      <span class="chip">${num(t.elapsed_seconds,2)} s</span>
    </div>
  </section>

  ${t.kind === 'contact_probe' ? `<section>
    <div class="card">
      <b>Contact probe.</b> This bypasses the planner on purpose. Contact schemas
      stay unafforded until a grasp certifies, so asking for the same thing
      <i>in words</i> is genuinely refused &mdash; see the refused run for
      "pick it up and hold it". The probe drives the physics directly so the
      grasp itself can be measured.
    </div>
  </section>` : ''}

  ${playerForTrace(t) ? `<section><h2>What the robot actually did</h2>
    ${playerForTrace(t)}
    <div class="note">The simulated trace, not the plan. Drag to orbit, scroll to
      zoom, space or the button to pause. Forward kinematics runs in the browser
      against the same model MuJoCo simulated${
        t.kind === 'contact_probe' ? ', block and support plate included' : ''}.</div>
  </section>` : (t.clip ? `<section><h2>What the robot actually did</h2>
    <img class="clip" src="./${esc(t.trace_id)}/${esc(t.clip)}" alt="${esc(t.prompt)}">
    <div class="note">Rendered clip &mdash; no 3D geometry was exported for this
      run. Run <code>python scripts/export_viewer.py</code> for playback.</div>
  </section>` : '')}

  ${renderMotionTree(t)}

  ${renderLibraryBreakdown(t.robot_id, (t.bindings || []).map(b => b.entry_id))}

  <section>
    <h2>Pipeline trace</h2>
    ${t.stages.map(s => `
      <details class="stage ${s.status === 'refused' ? 'refused' : ''}" ${s.status === 'refused' ? 'open' : ''}>
        <summary>
          <span class="dot"></span>
          <span class="name">${esc(s.name)}</span>
          <span class="say">${esc(s.summary)}</span>
          <span class="ms">${s.elapsed_ms >= 0.05 ? s.elapsed_ms.toFixed(1)+' ms' : ''}</span>
        </summary>
        ${Object.keys(s.detail || {}).length
          ? `<div class="body"><pre>${esc(JSON.stringify(s.detail, null, 2))}</pre></div>` : ''}
      </details>`).join('')}
    ${!t.accepted ? `<div class="card" style="margin-top:10px">
      <b class="bad">Refused at ${esc(t.failure.stage)}</b> &mdash; <code>${esc(t.failure.code)}</code>
      <div class="note">${esc(t.failure.detail)}</div></div>` : ''}
  </section>

  ${t.grasp ? `<section>
    <h2>Grasp &mdash; measured, not asserted</h2>
    <div class="grid">
      <div class="card"><div style="color:var(--muted);font-size:11px">verdict</div>
        <div class="${t.grasp.certified?'ok':'bad'}">${t.grasp.certified?'held':'not held'}</div></div>
      <div class="card"><div style="color:var(--muted);font-size:11px">opposition</div>
        <div class="${t.grasp.opposition_achieved?'ok':'bad'}">${t.grasp.opposition_achieved?'both sides':'never'}</div></div>
      <div class="card"><div style="color:var(--muted);font-size:11px">block</div>
        <div class="mono">${(t.grasp.block_size_m*1000).toFixed(0)} mm &middot; ${(t.grasp.block_mass_kg*1000).toFixed(0)} g</div></div>
      <div class="card"><div style="color:var(--muted);font-size:11px">lift</div>
        <div class="mono ${t.grasp.lift_height_m>=t.grasp.required_lift_m?'ok':'bad'}">${(t.grasp.lift_height_m*1000).toFixed(0)} mm <span style="color:var(--muted)">of ${(t.grasp.required_lift_m*1000).toFixed(0)} needed</span></div></div>
      <div class="card"><div style="color:var(--muted);font-size:11px">grip force</div>
        <div class="mono">${num(t.grasp.grip_force_n,1)} N</div></div>
      <div class="card"><div style="color:var(--muted);font-size:11px">penetration</div>
        <div class="mono">${(t.grasp.penetration_m*1000).toFixed(2)} mm</div></div>
      <div class="card"><div style="color:var(--muted);font-size:11px">equality constraints</div>
        <div class="${t.grasp.equality_constraints===0?'ok':'bad'}">${t.grasp.equality_constraints} &mdash; no weld</div></div>
    </div>
    ${t.grasp.violations.length ? `<table style="margin-top:12px">
      <thead><tr><th>gate</th><th>detail</th><th>measured</th><th>limit</th></tr></thead>
      <tbody>${t.grasp.violations.map(v=>`<tr><td class="bad">${esc(v.code)}</td>
        <td>${esc(v.detail)}</td><td class="mono">${num(v.measured,4)}</td>
        <td class="mono">${num(v.limit,4)}</td></tr>`).join('')}</tbody></table>`
      : `<div class="note">Every gate passed. The block is held by measured contact
         forces, not by an attachment &mdash; that is what the equality-constraint
         count is there to prove.</div>`}
    <div class="note">The block is sized from this gripper's own measured aperture
      and placed inside its own measured reach envelope. A scene in absolute metres
      would be the same mistake as a motion in absolute metres.</div>
  </section>`:''}

  ${segs.length ? `<section>
    <h2>Body-neutral reading &mdash; Talmy's slots</h2>
    ${segs.map((seg,i) => `<div class="card" style="margin-bottom:10px">
      <b>segment ${i+1}</b> <span class="hash">${esc(seg.schema)}</span>
      ${slotGrid(seg)}</div>`).join('')}
    <div class="card">
      <b>role-normalized hash</b>
      <div class="hash">${esc(t.role_normalized_hash)}</div>
      <div class="note">${others.length
        ? `Identical on ${others.length} other robot${others.length>1?'s':''}: ${others.map(o=>esc(o.robot_id)).join(', ')}. Same words, same meaning, different bodies.`
        : 'This prompt was only run on this robot.'}</div>
    </div>
  </section>` : ''}

  ${t.bindings?.length ? `<section>
    <h2>Bound to certified primitives</h2>
    <table><thead><tr><th>segment</th><th>schema</th><th class="mono">certified at</th><th>substituted</th></tr></thead>
    <tbody>${t.bindings.map(b=>`<tr>
      <td>${esc(b.segment_id)}</td><td>${esc(b.entry_id)}</td>
      <td class="mono">${esc(b.certified_remove ?? '—')}</td>
      <td>${b.substituted ? '<span class="warn">nearest region</span>' : 'exact'}</td>
    </tr>`).join('')}</tbody></table>
    ${t.bindings.some(b=>b.substituted) ? `<div class="note">A substituted segment is grounded at the region that actually certified, not the one requested &mdash; otherwise the certified label would be attached to a different motion.</div>`:''}
  </section>`:''}

  ${t.grounded ? `<section>
    <h2>Grounding &mdash; where the metres came from</h2>
    <div class="grid">
      ${Object.entries(t.grounded.grounded_against || {}).map(([k,v])=>`
        <div class="card"><div class="k" style="color:var(--muted);font-size:11px">${esc(k)}</div>
        <div style="font-family:ui-monospace,Menlo,monospace">${num(v,4)}</div></div>`).join('')}
      <div class="card"><div style="color:var(--muted);font-size:11px">duration</div>
        <div style="font-family:ui-monospace,Menlo,monospace">${num(t.grounded.duration_s,2)} s</div></div>
      <div class="card"><div style="color:var(--muted);font-size:11px">waypoints</div>
        <div style="font-family:ui-monospace,Menlo,monospace">${t.grounded.waypoints}</div></div>
    </div>
    <table style="margin-top:12px"><thead><tr><th>phase</th><th>kind</th><th>start</th><th>end</th></tr></thead>
      <tbody>${t.grounded.phases.map(p=>`<tr><td>${esc(p.phase_id)}</td><td>${esc(p.kind)}</td>
        <td>${num(p.start_s,2)}</td><td>${num(p.end_s,2)}</td></tr>`).join('')}</tbody></table>
  </section>`:''}

  ${t.certification ? `<section>
    <h2>Gates</h2>
    <div class="grid">
      <div class="card"><div style="color:var(--muted);font-size:11px">verdict</div>
        <div class="${t.certification.certified?'ok':'bad'}">${t.certification.certified?'certified':'rejected'}</div></div>
      <div class="card"><div style="color:var(--muted);font-size:11px">replays</div>
        <div>${t.certification.repeats} &middot; ${t.certification.replay_agreement?'<span class="ok">identical</span>':'<span class="bad">disagreed</span>'}</div></div>
      <div class="card"><div style="color:var(--muted);font-size:11px">tracking error</div>
        <div style="font-family:ui-monospace,Menlo,monospace">${(t.certification.tracking_error_m*1000).toFixed(2)} mm</div></div>
      <div class="card"><div style="color:var(--muted);font-size:11px">base drift</div>
        <div style="font-family:ui-monospace,Menlo,monospace">${(t.certification.base_drift_m*1000).toFixed(4)} mm</div></div>
    </div>
    ${t.certification.violations.length ? `<table style="margin-top:12px">
      <thead><tr><th>gate</th><th>detail</th><th>measured</th><th>limit</th></tr></thead>
      <tbody>${t.certification.violations.map(v=>`<tr><td class="bad">${esc(v.code)}</td>
        <td>${esc(v.detail)}</td><td class="mono">${num(v.measured,4)}</td>
        <td class="mono">${num(v.limit,4)}</td></tr>`).join('')}</tbody></table>`
      : `<div class="note">No gate raised an objection.</div>`}
  </section>`:''}

  <section>
    <h2>Provenance</h2>
    <div class="card">
      <div class="note">Base tree &mdash; the exact <code>rigby_v2</code> source this ran against.
        Neither v2 tree is tracked by git, so it is identified by content.</div>
      <div class="hash">${esc(t.provenance.base_tree.sha256)} &middot; ${t.provenance.base_tree.file_count} files</div>
      ${t.grounded ? `<div class="note" style="margin-top:8px">Sealed inventory</div>
        <div class="hash">${esc(t.grounded.inventory_sha256)}</div>
        <div class="note" style="margin-top:8px">Grounded program</div>
        <div class="hash">${esc(t.grounded.program_sha256)}</div>`:''}
    </div>
  </section>`;
}

function renderInvariance(){
  const groups = [...hashGroups().entries()]
    .map(([hash, rows]) => ({hash, rows, robots: new Set(rows.map(r=>r.robot_id)).size}))
    .sort((a,b) => b.robots - a.robots);
  return `
  <section>
    <h2>Schema invariance</h2>
    <div class="card">
      The load-bearing claim: <b>the same prompt must produce the same body-neutral
      reading on every robot</b>. Each group below is one role-normalized hash. A
      group spanning several robots is that claim holding; a prompt appearing under
      two different hashes would mean the semantic layer had learned something about
      a particular body.
    </div>
  </section>
  <section>
    ${groups.map(g => `
      <div class="card" style="margin-bottom:10px">
        <div style="display:flex;gap:10px;align-items:baseline;flex-wrap:wrap">
          <b>${esc(g.rows[0].prompt)}</b>
          <span class="chip">${g.robots} robot${g.robots>1?'s':''}</span>
          ${g.robots>1?'<span class="ok">one reading</span>':''}
        </div>
        <div class="hash" style="margin-top:5px">${esc(g.hash)}</div>
        <table style="margin-top:9px"><thead><tr><th>robot</th><th>reach</th><th>dof</th>
          <th>duration</th><th>outcome</th></tr></thead><tbody>
          ${g.rows.map(r=>`<tr>
            <td>${esc(r.robot_id)}</td>
            <td class="mono">${num(DATA.robots[r.robot_id]?.reach_radius_m,3)} m</td>
            <td class="mono">${DATA.robots[r.robot_id]?.dof ?? '—'}</td>
            <td class="mono">${num(r.grounded?.duration_s,1)} s</td>
            <td>${r.accepted?'<span class="ok">certified</span>':'<span class="bad">refused @ '+esc(r.failure?.stage)+'</span>'}</td>
          </tr>`).join('')}
        </tbody></table>
      </div>`).join('')}
  </section>`;
}

function renderContact(){
  const probes = DATA.traces.map((t,i)=>({t,i})).filter(x=>x.t.kind==='contact_probe');
  const held = probes.filter(x=>x.t.accepted).length;
  const jump = i => `view='runs';document.querySelectorAll('button.tab').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.view==='runs')));select(${i});return false`;
  return `
  <section><h2>Contact probes</h2>
    <div class="card">
      <b>${held} of ${probes.length} grippers complete a certified pick.</b>
      This is the partial part of the system, shown as such. The scene, the
      force-controlled closure and the five gates all work; reliable grasping
      across every gripper does not. Each failure names the claim that failed
      rather than reporting a generic error, and <b>every</b> attempt is rendered
      &mdash; a failed grasp is the more informative clip, because you can watch
      the block get knocked away instead of reading a gate code and guessing.
      <div class="note" style="margin-top:8px">Because contact schemas stay
        unafforded until a grasp certifies, asking for this in words is still
        refused. These probes drive the physics directly.</div>
    </div>
  </section>
  <section>
    <table><thead><tr><th>robot</th><th>effector</th><th>block</th><th>lift</th>
      <th>grip</th><th>penetration</th><th>outcome</th></tr></thead>
    <tbody>${probes.map(({t,i})=>`<tr>
      <td><a href="#" onclick="${jump(i)}" style="color:inherit">${esc(t.robot_id)}</a></td>
      <td>${esc(t.robot.effectors.map(e=>e.kind).join(', '))}</td>
      <td class="mono">${t.grasp ? (t.grasp.block_size_m*1000).toFixed(0)+' mm' : '&mdash;'}</td>
      <td class="mono">${t.grasp ? (t.grasp.lift_height_m*1000).toFixed(0)+' / '+(t.grasp.required_lift_m*1000).toFixed(0)+' mm' : '&mdash;'}</td>
      <td class="mono">${t.grasp ? num(t.grasp.grip_force_n,1)+' N' : '&mdash;'}</td>
      <td class="mono">${t.grasp ? (t.grasp.penetration_m*1000).toFixed(2)+' mm' : '&mdash;'}</td>
      <td>${t.accepted?'<span class="ok">held</span>':'<span class="bad">'+esc(t.failure?.code)+'</span>'}</td>
    </tr>`).join('')}</tbody></table>
  </section>`;
}

function renderLibrary(){
  return `
  <section><h2>Primitive libraries</h2>
    <div class="card">Each robot's library is baked once from its own measurements.
      A schema with no certified primitive is not a gap to be papered over &mdash; it is
      that robot's refusal boundary, and the binder quotes it back when asked.</div>
  </section>
  ${Object.entries(DATA.libraries).map(([robot, lib]) => `
    <section>
      <h2>${esc(robot)}</h2>
      <div class="meta">
        <span class="chip">certified <b>${lib.certified_count}</b>/${lib.attempted}</span>
        <span class="chip">yield <b>${lib.yield !== null ? (lib.yield*100).toFixed(0)+'%' : '—'}</b></span>
        <span class="chip">coverage <b>${lib.coverage !== null ? (lib.coverage*100).toFixed(0)+'%' : '—'}</b></span>
        <span class="chip">bake <b>${lib.elapsed_seconds}s</b></span>
        <span class="chip">reach <b>${num(DATA.robots[robot]?.reach_radius_m,3)} m</b></span>
      </div>
      <table style="margin-top:10px"><thead><tr><th>schema</th><th>certified regions</th></tr></thead>
        <tbody>${Object.entries(lib.certified).map(([k,v])=>`<tr>
          <td class="mono">${esc(k)}</td><td class="mono">${v.map(esc).join(' · ')}</td></tr>`).join('')}
        ${Object.entries(lib.refused).map(([k,v])=>`<tr>
          <td class="mono" style="color:var(--muted)">${esc(k)}</td>
          <td class="bad">refused &mdash; ${esc(v)}</td></tr>`).join('')}
        </tbody></table>
    </section>`).join('')}`;
}

function renderIntake(){
  const rows = DATA.intake || [];
  if (!rows.length) return '<section><div class="card">No intake record.</div></section>';
  const ok = rows.filter(r => r.accepted);
  const no = rows.filter(r => !r.accepted);
  const outside = rows.filter(r => r.origin === 'third-party');
  return `
  <section><h2>Uploads</h2>
    <div class="card">
      <b>${ok.length} of ${rows.length} models ingested</b>
      <div class="note">${outside.length} of them come from an outside project,
        pinned by commit and never committed here. A refusal is a result: the
        question is not whether every upload works, it is whether the ones that
        cannot be used are turned away for a reason that names the defect.</div>
    </div>
  </section>
  <section><h2>Accepted</h2>
    <table><thead><tr><th>robot</th><th>origin</th><th>class</th><th>dof</th>
      <th>reach</th><th>mass</th><th>effector</th></tr></thead>
    <tbody>${ok.map(r=>`<tr>
      <td class="mono">${esc(r.robot_id)}</td>
      <td>${esc(r.origin)}</td>
      <td class="mono">${esc(r.morphology_class||'')}</td>
      <td class="mono">${r.dofs}</td>
      <td class="mono">${num(r.reach_m,3)} m</td>
      <td class="mono">${num(r.mass_kg,2)} kg</td>
      <td class="mono">${(r.effectors||[]).map(e=>esc(e.kind)).join(', ')||'&mdash;'}</td>
    </tr>${(r.notes||[]).length?`<tr><td></td><td colspan="6">
      ${r.notes.map(n=>`<div class="note">recorded, not refused: ${esc(n)}</div>`).join('')}
    </td></tr>`:''}`).join('')}</tbody></table>
    <div class="note">A recorded note is a defect the pipeline found, decided it
      could work around, and wrote down rather than hid.</div>
  </section>
  <section><h2>Refused</h2>
    ${no.length ? no.map(r=>`<div class="card" style="margin-bottom:9px">
      <b class="bad">${esc(r.robot_id)}</b>
      <span class="mono"> &middot; ${esc(r.origin)} &middot; ${esc(r.code||r.error)}</span>
      <div class="note">${esc(r.detail)}</div>
    </div>`).join('') : '<div class="card">Nothing was refused.</div>'}
    <div class="note">Each of these names the measurement that failed and the
      value it took. None of them is "could not load".</div>
  </section>`;
}

function renderAudit(){
  if (!DATA.audit) return '<section><div class="card">No audit report found. Run <code>python -m rigby_general.audit --json docs/audit-report.json</code>.</div></section>';
  const a = DATA.audit;
  return `
  <section><h2>G-GEN-1</h2>
    <div class="card">
      <b class="${a.release_allowed?'ok':'bad'}">release_allowed: ${a.release_allowed}</b>
      <div class="note">A conjunction, never an average. One failing requirement is
        named; it is not traded off against a passing one.</div>
    </div>
  </section>
  <section>
    <table><thead><tr><th></th><th>requirement</th><th>measured</th><th>threshold</th></tr></thead>
    <tbody>${a.requirements.map(r=>`<tr>
      <td class="${r.passed?'ok':'bad'}">${r.passed?'PASS':'FAIL'}${r.load_bearing?' ★':''}</td>
      <td class="mono">${esc(r.id)}<div class="note">${esc(r.statement)}</div></td>
      <td class="mono">${num(r.measured,4)}</td>
      <td class="mono">${esc(r.comparator)} ${r.threshold}</td>
    </tr>`).join('')}</tbody></table>
    <div class="note">★ marks the load-bearing requirement: one prompt, one
      body-neutral reading, on every robot.</div>
  </section>`;
}

function render(){
  renderList();
  const el = document.getElementById('detail');
  el.innerHTML = view === 'runs' ? renderRun()
    : view === 'invariance' ? renderInvariance()
    : view === 'contact' ? renderContact()
    : view === 'library' ? renderLibrary()
    : view === 'explorer' ? renderExplorer()
    : view === 'intake' ? renderIntake() : renderAudit();
  // Markup is built as strings; live viewers attach only once it is in the DOM.
  mountPending();
  wireSeeks();
  if (view === 'explorer') wireExplorer();
  window.scrollTo({top:0});
}
function select(i){ current = i; render(); }
document.querySelectorAll('button.tab').forEach(b => b.onclick = () => {
  view = b.dataset.view;
  document.querySelectorAll('button.tab').forEach(x =>
    x.setAttribute('aria-selected', String(x === b)));
  render();
});
document.addEventListener('keydown', (e) => {
  if (e.code === 'Space' && VIEWERS.length && e.target === document.body) {
    e.preventDefault();
    VIEWERS[0].toggle();
  }
});
render();
</script>
</body>
</html>
"""


if __name__ == "__main__":
    raise SystemExit(main())
