"""Human calibration, dataset governance, and learned-model admission gates."""

from .admission import (
    HumanOutcome,
    InbetweeningAdmissionDecision,
    InbetweeningTrial,
    evaluate_inbetweening_admission,
)
from .datasets import (
    ClaimCategory,
    DatasetAuthorization,
    DatasetManifest,
    DatasetPolicyError,
    DatasetUse,
    DatasetUseRequest,
    authorize_dataset_use,
    load_dataset_manifest,
    load_dataset_registry,
)
from .io import (
    CompletedHumanStudyEvidence,
    HumanStudyBlueprintEvidence,
    HumanStudyEvidenceError,
    export_human_study_blueprint,
    import_completed_human_study,
    import_verified_human_study_collection,
)
from .media_study import (
    HumanReviewPackageError,
    HumanReviewPackageEvidence,
    SourceComparison,
    SourceMediaRecord,
    build_human_review_package,
    verify_human_review_package,
)
from .metrics import CalibrationMetrics, ConfidenceInterval, compute_calibration_metrics
from .motion_exit_study import (
    EXIT_DIMENSIONS,
    MINIMUM_EXIT_PAIRS,
    ExactDimensionResult,
    MatchedMotionPairSource,
    MotionExitPackageEvidence,
    MotionExitStudyError,
    MotionExitStudyResult,
    MotionVariantSource,
    build_motion_exit_study_package,
    import_verified_motion_exit_study,
)
from .study import (
    MINIMUM_PAIR_COUNT,
    MINIMUM_PAIRS_PER_FAMILY,
    SUPPORTED_ACTION_FAMILIES,
    CalibrationStudy,
    CalibrationStudyBlueprint,
    CalibrationStudyError,
    StudyValidation,
    build_synthetic_completed_study,
    construct_calibration_blueprint,
    selected_record,
    validate_calibration_study,
)

__all__ = [
    "EXIT_DIMENSIONS",
    "MINIMUM_EXIT_PAIRS",
    "MINIMUM_PAIRS_PER_FAMILY",
    "MINIMUM_PAIR_COUNT",
    "SUPPORTED_ACTION_FAMILIES",
    "CalibrationMetrics",
    "CalibrationStudy",
    "CalibrationStudyBlueprint",
    "CalibrationStudyError",
    "ClaimCategory",
    "CompletedHumanStudyEvidence",
    "ConfidenceInterval",
    "DatasetAuthorization",
    "DatasetManifest",
    "DatasetPolicyError",
    "DatasetUse",
    "DatasetUseRequest",
    "ExactDimensionResult",
    "HumanOutcome",
    "HumanReviewPackageError",
    "HumanReviewPackageEvidence",
    "HumanStudyBlueprintEvidence",
    "HumanStudyEvidenceError",
    "InbetweeningAdmissionDecision",
    "InbetweeningTrial",
    "MatchedMotionPairSource",
    "MotionExitPackageEvidence",
    "MotionExitStudyError",
    "MotionExitStudyResult",
    "MotionVariantSource",
    "SourceComparison",
    "SourceMediaRecord",
    "StudyValidation",
    "authorize_dataset_use",
    "build_human_review_package",
    "build_motion_exit_study_package",
    "build_synthetic_completed_study",
    "compute_calibration_metrics",
    "construct_calibration_blueprint",
    "evaluate_inbetweening_admission",
    "export_human_study_blueprint",
    "import_completed_human_study",
    "import_verified_human_study_collection",
    "import_verified_motion_exit_study",
    "load_dataset_manifest",
    "load_dataset_registry",
    "selected_record",
    "validate_calibration_study",
    "verify_human_review_package",
]
